version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    versioning-strategy: "increase-if-necessary"
    groups:
      next-toolchain:
        patterns:
          - "next"
          - "@next/*"
          - "eslint"
          - "eslint-config-next"
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-security:
        applies-to: "security-updates"
        patterns:
          - "*"

    ignore:
      - dependency-name: "eslint"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/New_York"
    versioning-strategy: "increase-if-necessary"
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-security:
        applies-to: "security-updates"
        patterns:
          - "*"