/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is generated by scripts/generate-airtable-data.ts
 * Run: npm run generate-airtable-data
 *
 * Generated at: 2026-01-18T19:39:13.097Z
 *
 * Contains distinct neighborhoods and tags from Airtable for entity detection
 * in the RAG query pipeline. These values are used to detect when users mention
 * specific neighborhoods or tags, enabling more precise filtering.
 */

/**
 * All distinct neighborhoods from Airtable.
 * Used by detectNeighborhoods() in entity-detection.ts.
 */
export const NEIGHBORHOODS = [
  "Arbor Glen",
  "Ashley Park",
  "Ballantyne",
  "Belmont",
  "Belmont (City)",
  "Bradfield Farms",
  "Carmel",
  "China Grove",
  "Closeburn - Glenkirk",
  "Collingwood",
  "Commonwealth Park",
  "Concord",
  "Cornelius",
  "Cotswold",
  "Dallas",
  "Davidson",
  "Davis Lake - Eastfield",
  "Denver",
  "Dilworth",
  "Druid Hills South",
  "East Forest",
  "Eastover",
  "Eastway",
  "Elizabeth",
  "Enderly Park",
  "Fort Mill",
  "Gastonia",
  "Grier Heights",
  "Harrisburg",
  "Hickory Grove",
  "Highland Creek",
  "Huntersville",
  "Independence Blvd",
  "Indian Land",
  "Indian Trail",
  "Kannapolis",
  "Kings Mountain",
  "Landis",
  "Lincoln Heights",
  "LoSo",
  "Lockwood",
  "Madison Park",
  "Matthews",
  "Midtown",
  "Mineral Springs",
  "Mint Hill",
  "Monroe",
  "Montclaire South",
  "Montford",
  "Mooresville",
  "Mount Holly",
  "Mountain Island",
  "Myers Park",
  "NoDa",
  "North Sharon Amity / Reddman Road",
  "Northwest Charlotte",
  "Oakhurst",
  "Oakview Terrace",
  "Olde Whitehall",
  "Optimist Park",
  "Pineville",
  "Piper Glen",
  "Plaza Midwood",
  "Providence Crossing",
  "Providence Park",
  "Quail Hollow",
  "Raintree",
  "Renaissance Park",
  "Rock Hill",
  "Sardis Crossing",
  "Sardis Woods",
  "Seversville",
  "Sheffield Park",
  "South End",
  "SouthPark",
  "Stallings",
  "Stanley",
  "Starmount",
  "Steele Creek",
  "Sugar Creek",
  "Tega Cay",
  "University City",
  "Uptown",
  "Washington Heights",
  "Waverly",
  "Waxhaw",
  "Wedgewood",
  "Wesley Heights",
  "West Sugar Creek",
] as const;

export type Neighborhood = (typeof NEIGHBORHOODS)[number];

/**
 * All distinct tags from Airtable.
 * Used by detectTags() in entity-detection.ts.
 */
export const TAGS = [
  "Black Owned",
  "Christian",
  "Great Date Spot",
  "Habesha",
  "Has Fireplace",
  "Hidden Gem",
  "Latino Owned",
  "Loose Leaf Tea",
  "Middle Eastern",
  "Outdoor Outlets",
] as const;

export type Tag = (typeof TAGS)[number];
