# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Third Places' do
  use_frameworks!

  # NOTE: Firebase is not currently used. Uncomment to enable push notifications.
  # pod 'Firebase/Messaging'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end