name: Build and Upload iOS App

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install CocoaPods dependencies
        run: |
          cd ios/src
          pod install

      - name: Create .p12 from key and certificate
        run: |
          echo "${{ secrets.IOS_DISTRIBUTION_KEY_BASE64 }}" | base64 --decode > ios_distribution.key
          echo "${{ secrets.IOS_DISTRIBUTION_PEM_BASE64 }}" | base64 --decode > ios_distribution.pem
          openssl pkcs12 -export -out ios_distribution.p12 -inkey ios_distribution.key -in ios_distribution.pem -passout pass:${{ secrets.P12_PASSWORD }}
          P12_BASE64=$(base64 -i ios_distribution.p12)
          echo "P12_BASE64=$P12_BASE64" >> $GITHUB_ENV
          rm ios_distribution.key ios_distribution.pem

      - name: Build and sign IPA
        uses: yukiarrr/ios-build-action@v1.12.0
        with:
          project-path: "ios/src/Third Places.xcodeproj"
          workspace-path: "ios/src/Third Places.xcworkspace"
          p12-base64: ${{ env.P12_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: "Apple Distribution"
          team-id: ${{ secrets.TEAM_ID }}
          export-method: app-store
          scheme: "Third Places"
          output-path: build/App.ipa

      - name: Upload to App Store Connect
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: build/App.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
