name: Trigger Refresh Airtable Operational Statuses

on:
  workflow_dispatch:

concurrency: 
  group: refresh-airtable-operational-statuses
  cancel-in-progress: true

jobs:
  trigger-refresh-operational-statuses:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Invoke PowerShell Script
        id: invoke_script
        shell: pwsh
        working-directory: ./scripts
        env:
          AZURE_FUNCTION_KEY: ${{ secrets.AZURE_FUNCTION_KEY }}
        continue-on-error: true
        run: |
          $FunctionUrl = "https://charlotte-third-places.azurewebsites.net/api/refresh-airtable-operational-statuses"
          $FunctionKey = "$Env:AZURE_FUNCTION_KEY"
          ./Invoke-AzureFunction.ps1 -FunctionUrl $FunctionUrl -FunctionKey $FunctionKey -TimeoutSeconds 1800

          if ($LASTEXITCODE -ne 0) {
            Write-Error "Azure Function call failed."
            exit $LASTEXITCODE
          } else {
            Write-Output "Azure Function call succeeded."
          }

      - name: Check Script Result
        if: always()
        run: |
          echo "Script execution completed with status: ${{ steps.invoke_script.outcome }}"
          if ("${{ steps.invoke_script.outcome }}" -ne "success") {
            exit 1
          }
