name: Trigger Enrich Airtable Base

on:
  workflow_dispatch:

# Ensures that only one instance of this workflow runs at a time
concurrency: 
  group: enrich-airtable-base
  cancel-in-progress: true

jobs:
  trigger-enrich-airtable-base:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Invoke PowerShell Script
        id: invoke_script
        shell: pwsh
        working-directory: ./scripts
        env:
          AZURE_FUNCTION_KEY: ${{ secrets.AZURE_FUNCTION_KEY }}
        run: |
          $FunctionUrl = "https://charlotte-third-places.azurewebsites.net/api/enrich-airtable-base"
          $FunctionKey = "$Env:AZURE_FUNCTION_KEY"
          $RequestBody = '{"TheMotto":"What is dead may never die, but rises again harder and stronger"}'
          ./Invoke-AzureFunction.ps1 -FunctionUrl $FunctionUrl -FunctionKey $FunctionKey -RequestBody $RequestBody -TimeoutSeconds 1800

          if ($LASTEXITCODE -ne 0) {
            Write-Error "Azure Function call failed."
            exit $LASTEXITCODE
          } else {
            Write-Output "Azure Function call succeeded."
          }

      - name: Check Script Result
        if: always()
        run: |
          echo "Script execution completed with outcome: ${{ steps.invoke_script.outcome }}"
          if ("${{ steps.invoke_script.outcome }}" != "success") {
            exit 1
          }
