name: Trigger Refresh Place Data

on:
  workflow_call:
    inputs:
      provider_type:
        description: 'Provider type for data refresh'
        required: false
        default: 'outscraper'
        type: string
      sequential_mode:
        description: 'Whether to run in sequential mode'
        required: false
        default: 'false'
        type: string
      force_refresh:
        description: 'Force refresh of all data'
        required: false
        default: 'false'
        type: string
      city:
        description: 'City to refresh data for'
        required: false
        default: 'charlotte'
        type: string
  workflow_dispatch:
    inputs:
      provider_type:
        description: 'Provider type for data refresh'
        required: false
        default: 'outscraper'
        type: string
      sequential_mode:
        description: 'Whether to run in sequential mode'
        required: false
        default: 'false'
        type: string
      force_refresh:
        description: 'Force refresh of all data'
        required: false
        default: 'false'
        type: string
      city:
        description: 'City to refresh data for'
        required: false
        default: 'charlotte'
        type: string

concurrency: 
  group: refresh-place-data
  cancel-in-progress: true

jobs:
  trigger-refresh-place-data:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Invoke PowerShell Script
        id: invoke_script
        working-directory: ./scripts
        shell: pwsh
        env:
          AZURE_FUNCTION_KEY: ${{ secrets.AZURE_FUNCTION_KEY }}
        run: |
          $providerType = "${{ github.event.inputs.provider_type || 'outscraper' }}"
          $sequentialMode = "${{ github.event.inputs.sequential_mode || 'false' }}"
          $forceRefresh = "${{ github.event.inputs.force_refresh || 'false' }}"
          $city = "${{ github.event.inputs.city || 'charlotte' }}"
          
          $FunctionUrl = "https://third-places-data.azurewebsites.net/api/refresh-place-data?provider_type=$providerType&sequential_mode=$sequentialMode&force_refresh=$forceRefresh&city=$city"
          
          Write-Host "Using orchestrator URL: $FunctionUrl"
          
          ./Invoke-AzureDurableFunction.ps1 -FunctionUrl $FunctionUrl -FunctionKey "$Env:AZURE_FUNCTION_KEY" -TimeoutSeconds 7200

          if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
          }

      - name: Check Script Result
        if: always()
        run: |
          echo "Script execution completed with status: ${{ steps.invoke_script.outcome }}"
          if ("${{ steps.invoke_script.outcome }}" -ne "success") {
            exit 1
          }