name: Trigger Get Outscraper Reviews

on:
  workflow_call:
  workflow_dispatch:

concurrency: 
  group: get-outscraper-reviews
  cancel-in-progress: true

jobs:
  trigger-get-outscraper-reviews:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Invoke PowerShell Script
        id: invoke_script
        working-directory: ./scripts
        shell: pwsh
        env:
          AZURE_FUNCTION_KEY: ${{ secrets.AZURE_FUNCTION_KEY }}
        run: |
          ./Invoke-AzureDurableFunction.ps1 -OrchestratorUrl "https://third-places-data.azurewebsites.net/api/orchestrators/get_outscraper_reviews_orchestrator" -FunctionKey "$Env:AZURE_FUNCTION_KEY" -TimeoutSeconds 7200

          if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
          }

      - name: Check Script Result
        if: always()
        run: |
          echo "Script execution completed with status: ${{ steps.invoke_script.outcome }}"
          if ("${{ steps.invoke_script.outcome }}" -ne "success") {
            exit 1
          }