name: Trigger GetOutscraperReviews Azure Function

on:
  workflow_dispatch:

# Ensures that only one instance of this workflow runs at a time
concurrency: 
  group: get-outscraper-reviews
  cancel-in-progress: true

jobs:
  trigger-get-outscraper-reviews:
    runs-on: ubuntu-latest
    steps:    
      - name: Trigger Azure Function
        run: |
          #!/bin/bash
          set -euo pipefail
      
          API_URL="https://charlotte-third-places.azurewebsites.net/api/get-outscraper-reviews"
      
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -H "x-functions-key: ${{ secrets.AZURE_FUNCTION_KEY }}" \
            "$API_URL")
      
          http_status=$(tail -n1 <<< "$response")
          response_body=$(sed '$ d' <<< "$response")
      
          echo "HTTP Status: $http_status"
          echo "Response Body: $response_body"
      
          if [[ $http_status -ge 200 && $http_status -lt 300 ]]; then
              echo "Action succeeded: GetOutscraperReviews successfully executed."
          else
              echo "Action failed: Unable to process GetOutscraperReviews."
              echo "HTTP Status: $http_status"
              echo "Response Body: $response_body"
              exit 1
          fi
        shell: bash
