name: Trigger Enrich Airtable Base

on:
  workflow_call:
    inputs:
      provider_type:
        description: 'Provider type for data enrichment'
        required: false
        default: 'outscraper'
        type: string
      sequential_mode:
        description: 'Whether to run in sequential mode'
        required: false
        default: 'false'
        type: string
      force_refresh:
        description: 'Force refresh of all data'
        required: false
        default: 'false'
        type: string
      insufficient_only:
        description: 'Only process records with insufficient data'
        required: false
        default: 'true'
        type: string
      city:
        description: 'City to enrich data for'
        required: false
        default: 'charlotte'
        type: string
  workflow_dispatch:
    inputs:
      provider_type:
        description: 'Provider type for data enrichment'
        required: false
        default: 'outscraper'
        type: string
      sequential_mode:
        description: 'Whether to run in sequential mode'
        required: false
        default: 'false'
        type: string
      force_refresh:
        description: 'Force refresh of all data'
        required: false
        default: 'false'
        type: string
      insufficient_only:
        description: 'Only process records with insufficient data'
        required: false
        default: 'true'
        type: string
      city:
        description: 'City to enrich data for'
        required: false
        default: 'charlotte'
        type: string

# Ensures that only one instance of this workflow runs at a time
concurrency: 
  group: enrich-airtable-base
  cancel-in-progress: true

jobs:
  trigger-enrich-airtable-base:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Invoke PowerShell Script
        id: invoke_script
        shell: pwsh
        working-directory: ./scripts
        env:
          AZURE_FUNCTION_KEY: ${{ secrets.AZURE_FUNCTION_KEY }}
        run: |
          $providerType = "${{ github.event.inputs.provider_type || 'outscraper' }}"
          $sequentialMode = "${{ github.event.inputs.sequential_mode || 'false' }}"
          $forceRefresh = "${{ github.event.inputs.force_refresh || 'false' }}"
          $insufficientOnly = "${{ github.event.inputs.insufficient_only || 'true' }}"
          $city = "${{ github.event.inputs.city || 'charlotte' }}"
          
          $FunctionUrl = "https://third-places-data.azurewebsites.net/api/enrich-airtable-base?provider_type=$providerType&sequential_mode=$sequentialMode&force_refresh=$forceRefresh&insufficient_only=$insufficientOnly&city=$city"
          
          Write-Host "Using function URL: $FunctionUrl"
          
          $FunctionKey = "$Env:AZURE_FUNCTION_KEY"
          ./Invoke-AzureDurableFunction.ps1 -OrchestratorUrl $FunctionUrl -FunctionKey $FunctionKey -TimeoutSeconds 1800

          if ($LASTEXITCODE -ne 0) {
            Write-Error "Azure Function call failed."
            exit $LASTEXITCODE
          } else {
            Write-Output "Azure Function call succeeded."
          }

      - name: Check Script Result
        if: always()
        run: |
          echo "Script execution completed with status: ${{ steps.invoke_script.outcome }}"
          if ("${{ steps.invoke_script.outcome }}" -ne "success") {
            exit 1
          }